name: build
# on:
#   push:
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: cargo build --release
      - name: Archive release build
        uses: actions/upload-artifact@v2
        with:
          name: release-build
          path: |
            target/release/directory-permission-watcher
            target/release/directory-permission-watcher.d
